# Generated by Django 3.1.2 on 2020-10-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='me',
            new_name='user_from',
        ),
    ]
