# Generated by Django 3.1.2 on 2020-10-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201006_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='views',
            field=models.BooleanField(default=False),
        ),
    ]
